import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    "_id": uuid(),
    "product_name": "rutrum neque aenean auctor gravida",
    "product_description": "Fusce consequat. Nulla nisl. Nunc nisl.\n\nDuis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.",
    "product_price": 1252,
    "product_category": "necklace",
    "product_brand": "Devpoint",
    "product_image": "https://staticimg.titan.co.in/Tanishq/Catalog/50D2P2NYZAA32_1.jpg?impolicy=pqmed&imwidth=640",
    "product_rating": 1.2,
    "product_reviews": 462,
    "product_color": "blue",
    "product_size": "small",
    "product_material": "platinum",
    "product_occasion": "Bridal",
    "product_prevPrice": 2022,
    "product_isFavorite": "true",
    "product_isCart": "false",
    "product_isBadge": "New"
  },
  {
    "_id": uuid(),
    "product_name": "diam erat fermentum",
    "product_description": "In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.\n\nAliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.\n\nSed ante. Vivamus tortor. Duis mattis egestas metus.",
    "product_price": 666,
    "product_category": "ring",
    "product_brand": "Trilith",
    "product_image": "https://staticimg.titan.co.in/Tanishq/Catalog/50D2I1FKTAA02_1.jpg?impolicy=pqmed&imwidth=640",
    "product_rating": 1.6,
    "product_reviews": 647,
    "product_color": "Rosegold",
    "product_size": "medium",
    "product_material": "silver",
    "product_occasion": "Modern",
    "product_prevPrice": 1743,
    "product_isFavorite": "true",
    "product_isCart": "false",
    "product_isBadge": "Trending"
  },
  {
    "_id": uuid(),
    "product_name": "tincidunt nulla mollis",
    "product_description": "Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.\n\nIn quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.",
    "product_price": 683,
    "product_category": "ring",
    "product_brand": "Jabbercube",
    "product_image": "https://cdn.shopify.com/s/files/1/0061/8378/0442/products/R016_1_1024x1024.jpg?v=1653116839",
    "product_rating": 2.5,
    "product_reviews": 635,
    "product_color": "Silver",
    "product_size": "extra large",
    "product_material": "silver",
    "product_occasion": "Engagement",
    "product_prevPrice": 2452,
    "product_isFavorite": "true",
    "product_isCart": "false",
    "product_isBadge": "New"
  },
  {
    "_id": uuid(),
    "product_name": "sapien iaculis",
    "product_description": "Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.\n\nCras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.\n\nQuisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.",
    "product_price": 1471,
    "product_category": "bracelet",
    "product_brand": "Jabberstorm",
    "product_image": "https://images.cltstatic.com/media/product/350/AT00109-SS0000-antique-veliammas-kitty-party-bracelet-in--silver-prd-1-base.jpg",
    "product_rating": 3.7,
    "product_reviews": 292,
    "product_color": "Silver",
    "product_size": "medium",
    "product_material": "silver",
    "product_occasion": "Office",
    "product_prevPrice": 1758,
    "product_isFavorite": "true",
    "product_isCart": "false",
    "product_isBadge": "New"
  },
  {
    "_id": uuid(),
    "product_name": "turpis integer aliquet massa",
    "product_description": "Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.",
    "product_price": 1399,
    "product_category": "ring",
    "product_brand": "Voonder",
    "product_image": "https://staticimg.titan.co.in/Tanishq/Catalog/511920FCMAA00.jpg?impolicy=pqmed&imwidth=640",
    "product_rating": 3.4,
    "product_reviews": 9,
    "product_color": "Platinum",
    "product_size": "large",
    "product_material": "gold",
    "product_occasion": "Casual",
    "product_prevPrice": 2362,
    "product_isFavorite": "false",
    "product_isCart": "false",
    "product_isBadge": "New"
  },
  {
    "_id": uuid(),
    "product_name": "nunc vestibulum",
    "product_description": "Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.\n\nQuisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.\n\nPhasellus in felis. Donec semper sapien a libero. Nam dui.",
    "product_price": 1027,
    "product_category": "bracelet",
    "product_brand": "Babbleset",
    "product_image": "https://images.cltstatic.com/media/product/350/AT00238-SS0000-hall-of-fame-bracelet-in--silver-prd-1-base.jpg",
    "product_rating": 4.9,
    "product_reviews": 803,
    "product_color": "Platinum",
    "product_size": "large",
    "product_material": "platinum",
    "product_occasion": "Engagement",
    "product_prevPrice": 2063,
    "product_isFavorite": "false",
    "product_isCart": "false",
    "product_isBadge": "Trending"
  },
  {
    "_id": uuid(),
    "product_name": "morbi quis tortor",
    "product_description": "Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.\n\nIn hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.\n\nAliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.",
    "product_price": 769,
    "product_category": "bracelet",
    "product_brand": "Devify",
    "product_image": "https://staticimg.titan.co.in/Tanishq/Catalog/50D1I2BAHAA02_1.jpg?impolicy=pqmed&imwidth=640",
    "product_rating": 4.7,
    "product_reviews": 146,
    "product_color": "Rosegold",
    "product_size": "large",
    "product_material": "diamond",
    "product_occasion": "Office",
    "product_prevPrice": 2150,
    "product_isFavorite": "false",
    "product_isCart": "false",
    "product_isBadge": "New"
  },
  {
    "_id": uuid(),
    "product_name": "condimentum curabitur in libero ut",
    "product_description": "Phasellus in felis. Donec semper sapien a libero. Nam dui.",
    "product_price": 916.08,
    "product_category": "ring",
    "product_brand": "Browsedrive",
    "product_image": "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcRZFhGZgaIru-JPQ0JB7euuPU0OSluCJe7tfNgfVuRCppkDXC_sFldMTQC9mLoHByspwbVS2jnHu84nJk-AXTjNIyuVo-xe4uSD87n0ehcF7aEF2qCh3CYIlO9W9VBZjolxMg&usqp=CAc",
    "product_rating": 5.0,
    "product_reviews": 503,
    "product_color": "green",
    "product_size": "medium",
    "product_material": "silver",
    "product_occasion": "Office",
    "product_prevPrice": 2113.625,
    "product_isFavorite": "false",
    "product_isCart": "false",
    "product_isBadge": "New"
  },
 
  {
    "_id": uuid(),
    "product_name": "pellentesque",
    "product_description": "Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.\n\nEtiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.\n\nPraesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.",
    "product_price": 998.93,
    "product_category": "bracelet",
    "product_brand": "Jabbercube",
    "product_image": "https://staticimg.titan.co.in/Tanishq/Catalog/50D2A1BBMAA09_1.jpg?impolicy=pqmed&imwidth=640",
    "product_rating": 4.1,
    "product_reviews": 821,
    "product_color": "Silver",
    "product_size": "medium",
    "product_material": "diamond",
    "product_occasion": "Bridal",
    "product_prevPrice": 1877.457,
    "product_isFavorite": "false",
    "product_isCart": "false",
    "product_isBadge": "New"
  },
  {
    "_id": uuid(),
    "product_name": "morbi vestibulum velit",
    "product_description": "Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.\n\nCras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.\n\nProin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.",
    "product_price": 746.06,
    "product_category": "bracelet",
    "product_brand": "Photobug",
    "product_image": "https://images.cltstatic.com/media/product/350/AT00239-SS0000-walking-on-air-leaf-bracelet-in--silver-prd-1-model.jpg",
    "product_rating": 2.6,
    "product_reviews": 765,
    "product_color": "green",
    "product_size": "large",
    "product_material": "silver",
    "product_occasion": "Casual",
    "product_prevPrice": 1550.009,
    "product_isFavorite": "true",
    "product_isCart": "false",
    "product_isBadge": ""
  },
  {
    "_id": uuid(),
    "product_name": "in",
    "product_description": "Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.\n\nNullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.\n\nIn quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.",
    "product_price": 228.58,
    "product_category": "necklace",
    "product_brand": "Jetpulse",
    "product_image": "https://staticimg.titan.co.in/Tanishq/Catalog/50D2FFNGBAA02_1.jpg?impolicy=pqmed&imwidth=640",
    "product_rating": 4.7,
    "product_reviews": 836,
    "product_color": "blue",
    "product_size": "small",
    "product_material": "gold",
    "product_occasion": "Bridal",
    "product_prevPrice": 2357.507,
    "product_isFavorite": "false",
    "product_isCart": "false",
    "product_isBadge": "New"
  },
  {
    "_id": uuid(),
    "product_name": "quis orci",
    "product_description": "Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.",
    "product_price": 497.2,
    "product_category": "earring",
    "product_brand": "Bluejam",
    "product_image": "https://staticimg.titan.co.in/Tanishq/Catalog/50D2FFHORAGA09_1.jpg?impolicy=pqmed&imwidth=640",
    "product_rating": 4.4,
    "product_reviews": 804,
    "product_color": "Rosegold",
    "product_size": "large",
    "product_material": "platinum",
    "product_occasion": "Casual",
    "product_prevPrice": 2011.614,
    "product_isFavorite": "false",
    "product_isCart": "false",
    "product_isBadge": ""
  },
  {
    "_id": uuid(),
    "product_name": "cubilia curae donec pharetra magna",
    "product_description": "Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.",
    "product_price": 676.84,
    "product_category": "earring",
    "product_brand": "Feednation",
    "product_image": "https://staticimg.titan.co.in/Tanishq/Catalog/502011HQYAAA02_1.jpg?impolicy=pqmed&imwidth=640",
    "product_rating": 3.3,
    "product_reviews": 210,
    "product_color": "blue",
    "product_size": "extra large",
    "product_material": "silver",
    "product_occasion": "Bridal",
    "product_prevPrice": 1900.74,
    "product_isFavorite": "true",
    "product_isCart": "false",
    "product_isBadge": "Trending"
  },
  {
    "_id": uuid(),
    "product_name": "ut ultrices vel augue",
    "product_description": "Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.\n\nIn hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.\n\nAliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.",
    "product_price": 1143.0,
    "product_category": "necklace",
    "product_brand": "Shufflebeat",
    "product_image": "https://staticimg.titan.co.in/Tanishq/Catalog/50D2FFNGMAA32_1.jpg?impolicy=pqmed&imwidth=640",
    "product_rating": 2.8,
    "product_reviews": 960,
    "product_color": "Rosegold",
    "product_size": "extra large",
    "product_material": "gold",
    "product_occasion": "Traditional",
    "product_prevPrice": 2372.297,
    "product_isFavorite": "true",
    "product_isCart": "false",
    "product_isBadge": "New"
  },
  {
    "_id": uuid(),
    "product_name": "rutrum nulla tellus",
    "product_description": "Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.\n\nNullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.",
    "product_price": 1271.29,
    "product_category": "bracelet",
    "product_brand": "Skimia",
    "product_image": "https://staticimg.titan.co.in/Mia/Catalog/552818BMVAE09_1.jpg?impolicy=pqmed&imwidth=640",
    "product_rating": 2.9,
    "product_reviews": 127,
    "product_color": "Rosegold",
    "product_size": "small",
    "product_material": "diamond",
    "product_occasion": "Traditional",
    "product_prevPrice": 2465.83,
    "product_isFavorite": "true",
    "product_isCart": "false",
    "product_isBadge": "New"
  },
  {
    "_id": uuid(),
    "product_name": "felis eu sapien cursus vestibulum",
    "product_description": "Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.\n\nDuis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.\n\nMauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.",
    "product_price": 1362.9,
    "product_category": "bracelet",
    "product_brand": "Photobug",
    "product_image": "https://staticimg.titan.co.in/Mia/Catalog/552821BFUAE29_1.jpg?impolicy=pqmed&imwidth=640",
    "product_rating": 1.4,
    "product_reviews": 865,
    "product_color": "pink",
    "product_size": "extra large",
    "product_material": "diamond",
    "product_occasion": "Traditional",
    "product_prevPrice": 2333.821,
    "product_isFavorite": "true",
    "product_isCart": "false",
    "product_isBadge": ""
  },
  {
    "_id": uuid(),
    "product_name": "orci",
    "product_description": "Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.\n\nPraesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.\n\nMorbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.",
    "product_price": 766.78,
    "product_category": "ring",
    "product_brand": "Voolith",
    "product_image": "https://staticimg.titan.co.in/Tanishq/Catalog/501050FEOAA11_1.jpg?impolicy=pqmed&imwidth=640",
    "product_rating": 4.2,
    "product_reviews": 652,
    "product_color": "green",
    "product_size": "large",
    "product_material": "gold",
    "product_occasion": "Modern",
    "product_prevPrice": 1651.96,
    "product_isFavorite": "false",
    "product_isCart": "false",
    "product_isBadge": ""
  },
  {
    "_id": uuid(),
    "product_name": "sapien urna pretium nisl ut",
    "product_description": "Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.",
    "product_price": 560.18,
    "product_category": "earring",
    "product_brand": "Reallinks",
    "product_image": "https://staticimg.titan.co.in/Tanishq/Catalog/502015HIMAAA02.jpg?impolicy=pqmed&imwidth=640",
    "product_rating": 3.8,
    "product_reviews": 976,
    "product_color": "Gold",
    "product_size": "small",
    "product_material": "platinum",
    "product_occasion": "Casual",
    "product_prevPrice": 2341.315,
    "product_isFavorite": "true",
    "product_isCart": "false",
    "product_isBadge": "Trending"
  },
  {
    "_id": uuid(),
    "product_name": "maecenas",
    "product_description": "Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.\n\nSed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.\n\nPellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.",
    "product_price": 344.43,
    "product_category": "earring",
    "product_brand": "Avaveo",
    "product_image": "https://staticimg.titan.co.in/Tanishq/Catalog/502995HZQAAA02_1.jpg?impolicy=pqmed&imwidth=640",
    "product_rating": 4.7,
    "product_reviews": 952,
    "product_color": "Silver",
    "product_size": "small",
    "product_material": "diamond",
    "product_occasion": "Engagement",
    "product_prevPrice": 2034.273,
    "product_isFavorite": "true",
    "product_isCart": "false",
    "product_isBadge": "New"
  },
  
  {
    "_id": uuid(),
    "product_name": "porttitor lacus at",
    "product_description": "In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.\n\nMaecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.\n\nMaecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.",
    "product_price": 1189.75,
    "product_category": "necklace",
    "product_brand": "Snaptags",
    "product_image": "https://staticimg.titan.co.in/Tanishq/Catalog/50D2I2NCGAA29.jpg?impolicy=pqmed&imwidth=640",
    "product_rating": 3.5,
    "product_reviews": 390,
    "product_color": "Platinum",
    "product_size": "small",
    "product_material": "diamond",
    "product_occasion": "Casual",
    "product_prevPrice": 1784.824,
    "product_isFavorite": "true",
    "product_isCart": "false",
    "product_isBadge": "Trending"
  },
  {
    "_id": uuid(),
    "product_name": "magna vulputate luctus cum",
    "product_description": "Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.",
    "product_price": 501.03,
    "product_category": "earring",
    "product_brand": "Flashdog",
    "product_image": "https://staticimg.titan.co.in/Tanishq/Catalog/502995HZUAAA02_1.jpg?impolicy=pqmed&imwidth=640",
    "product_rating": 3.9,
    "product_reviews": 759,
    "product_color": "Silver",
    "product_size": "large",
    "product_material": "silver",
    "product_occasion": "Casual",
    "product_prevPrice": 1527.828,
    "product_isFavorite": "true",
    "product_isCart": "false",
    "product_isBadge": "Trending"
  },
  {
    "_id": uuid(),
    "product_name": "nec",
    "product_description": "Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.",
    "product_price": 1444.91,
    "product_category": "bracelet",
    "product_brand": "InnoZ",
    "product_image": "https://staticimg.titan.co.in/Mia/Catalog/552822BPUAE09_1.jpg?impolicy=pqmed&imwidth=640",
    "product_rating": 1.3,
    "product_reviews": 838,
    "product_color": "Rosegold",
    "product_size": "small",
    "product_material": "gold",
    "product_occasion": "Modern",
    "product_prevPrice": 1535.045,
    "product_isFavorite": "true",
    "product_isCart": "false",
    "product_isBadge": "Trending"
  },
  {
    "_id": uuid(),
    "product_name": "ligula suspendisse ornare consequat lectus",
    "product_description": "Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.\n\nAenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.\n\nCurabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.",
    "product_price": 1065.32,
    "product_category": "ring",
    "product_brand": "Bubbletube",
    "product_image": "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcRi3iX8UrlFJNFQNZmGXZQzof4jqX07MY6762iTsrJw7ggDMwndNnBjRRnbqlwAvtpvhj853VEwekVQC0InmsJMRfMPWlPChYq2rQf_n7Aguo6Wd34YX2CwooMoOR29Bt6Qiq4b&usqp=CAc",
    "product_rating": 1.5,
    "product_reviews": 889,
    "product_color": "pink",
    "product_size": "large",
    "product_material": "silver",
    "product_occasion": "Office",
    "product_prevPrice": 1892.554,
    "product_isFavorite": "false",
    "product_isCart": "false",
    "product_isBadge": ""
  },
  {
    "_id": uuid(),
    "product_name": "tincidunt lacus at velit",
    "product_description": "Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.",
    "product_price": 661.29,
    "product_category": "necklace",
    "product_brand": "Photobug",
    "product_image": "https://staticimg.titan.co.in/Tanishq/Catalog/50D1D2NJUAA09_1.jpg?impolicy=pqmed&imwidth=640",
    "product_rating": 3.8,
    "product_reviews": 532,
    "product_color": "Platinum",
    "product_size": "small",
    "product_material": "diamond",
    "product_occasion": "Modern",
    "product_prevPrice": 2059.733,
    "product_isFavorite": "false",
    "product_isCart": "false",
    "product_isBadge": "Trending"
  },
  {
    "_id": uuid(),
    "product_name": "nibh",
    "product_description": "Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.",
    "product_price": 1327.49,
    "product_category": "earring",
    "product_brand": "Mita",
    "product_image": "https://staticimg.titan.co.in/Tanishq/Catalog/502213HJNAAA09_1.jpg?impolicy=pqmed&imwidth=640",
    "product_rating": 2.4,
    "product_reviews": 444,
    "product_color": "Silver",
    "product_size": "large",
    "product_material": "silver",
    "product_occasion": "Traditional",
    "product_prevPrice": 1698.323,
    "product_isFavorite": "false",
    "product_isCart": "false",
    "product_isBadge": "New"
  },
  {
    "_id": uuid(),
    "product_name": "ac",
    "product_description": "Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.",
    "product_price": 1177.04,
    "product_category": "ring",
    "product_brand": "Feedfire",
    "product_image": "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcSOiPJdSRvaKOo8xSzZTbcFsE_PPjy54_hP4ufWkc8GWgZaBaUp2Wiy_-Ymci_WutwjnjNLaaknucalY6BKPwHf-11BA0LwKlim7h1O61LntDSMy3XH4wpGL_Z6eIewFTcRyA&usqp=CAc",
    "product_rating": 2.8,
    "product_reviews": 898,
    "product_color": "pink",
    "product_size": "extra large",
    "product_material": "platinum",
    "product_occasion": "Bridal",
    "product_prevPrice": 2412.791,
    "product_isFavorite": "false",
    "product_isCart": "false",
    "product_isBadge": "New"
  },
  {
    "_id": uuid(),
    "product_name": "ac diam cras pellentesque volutpat",
    "product_description": "Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.\n\nInteger tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.",
    "product_price": 699.85,
    "product_category": "ring",
    "product_brand": "Oba",
    "product_image": "https://staticimg.titan.co.in/Tanishq/Catalog/51T404FGNAA00_1.jpg?impolicy=pqmed&imwidth=640",
    "product_rating": 2.5,
    "product_reviews": 945,
    "product_color": "blue",
    "product_size": "extra large",
    "product_material": "gold",
    "product_occasion": "Traditional",
    "product_prevPrice": 1730.693,
    "product_isFavorite": "false",
    "product_isCart": "false",
    "product_isBadge": "Trending"
  },
  {
    "_id": uuid(),
    "product_name": "vehicula condimentum curabitur",
    "product_description": "Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.\n\nPraesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.\n\nCras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
    "product_price": 707.83,
    "product_category": "bracelet",
    "product_brand": "Dabjam",
    "product_image": "https://staticimg.titan.co.in/Mia/Catalog/552822BRSAE09_1.jpg?impolicy=pqmed&imwidth=640",
    "product_rating": 1.8,
    "product_reviews": 218,
    "product_color": "green",
    "product_size": "large",
    "product_material": "gold",
    "product_occasion": "Bridal",
    "product_prevPrice": 1757.519,
    "product_isFavorite": "true",
    "product_isCart": "false",
    "product_isBadge": ""
  },
  {
    "_id": uuid(),
    "product_name": "vestibulum",
    "product_description": "Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.",
    "product_price": 1267.21,
    "product_category": "bracelet",
    "product_brand": "Twinte",
    "product_image": "https://images.cltstatic.com/media/product/350/AT00177-SS0000-a-lazy-morning-bracelet-in--silver-prd-1-model.jpg",
    "product_rating": 3.6,
    "product_reviews": 334,
    "product_color": "Silver",
    "product_size": "extra large",
    "product_material": "silver",
    "product_occasion": "Casual",
    "product_prevPrice": 1944.478,
    "product_isFavorite": "true",
    "product_isCart": "false",
    "product_isBadge": "Trending"
  },
  {
    "_id": uuid(),
    "product_name": "in ante",
    "product_description": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.\n\nVestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.\n\nDuis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.",
    "product_price": 686.61,
    "product_category": "bracelet",
    "product_brand": "Tagcat",
    "product_image": "https://staticimg.titan.co.in/Tanishq/Catalog/503119BOXAA32_1.jpg?impolicy=pqmed&imwidth=640",
    "product_rating": 3.5,
    "product_reviews": 890,
    "product_color": "Rosegold",
    "product_size": "large",
    "product_material": "diamond",
    "product_occasion": "Office",
    "product_prevPrice": 2447.063,
    "product_isFavorite": "false",
    "product_isCart": "false",
    "product_isBadge": "Trending"
  },
  {
    "_id": uuid(),
    "product_name": "semper porta",
    "product_description": "Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.\n\nDonec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.",
    "product_price": 712.59,
    "product_category": "bracelet",
    "product_brand": "Voolith",
    "product_image": "https://images.cltstatic.com/media/product/350/AT00261-SS0000-oxidised-rise-above-fear-black-bead-bracelet-in--silver-prd-1-model.jpg",
    "product_rating": 3.3,
    "product_reviews": 499,
    "product_color": "green",
    "product_size": "large",
    "product_material": "silver",
    "product_occasion": "Office",
    "product_prevPrice": 2112.367,
    "product_isFavorite": "true",
    "product_isCart": "false",
    "product_isBadge": "New"
  },
  {
    "_id": uuid(),
    "product_name": "dictumst morbi",
    "product_description": "Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.\n\nIn quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.",
    "product_price": 1256.04,
    "product_category": "necklace",
    "product_brand": "Demivee",
    "product_image": "https://images.cltstatic.com/media/product/350/AL00294-SS0000-elizabeth-bennet-necklace-in--oxidised-silver-prd-1-model.jpg",
    "product_rating": 2.4,
    "product_reviews": 719,
    "product_color": "Rosegold",
    "product_size": "large",
    "product_material": "silver",
    "product_occasion": "Casual",
    "product_prevPrice": 1796.055,
    "product_isFavorite": "true",
    "product_isCart": "false",
    "product_isBadge": "Trending"
  },
  {
    "_id": uuid(),
    "product_name": "bibendum imperdiet nullam orci pede",
    "product_description": "Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.",
    "product_price": 1378.28,
    "product_category": "ring",
    "product_brand": "InnoZ",
    "product_image": "https://staticimg.titan.co.in/Tanishq/Catalog/50D1I2FGDAA09_1.jpg?impolicy=pqmed&imwidth=640",
    "product_rating": 3.2,
    "product_reviews": 50,
    "product_color": "Rosegold",
    "product_size": "large",
    "product_material": "diamond",
    "product_occasion": "Engagement",
    "product_prevPrice": 2364.38,
    "product_isFavorite": "true",
    "product_isCart": "false",
    "product_isBadge": ""
  },
  {
    "_id": uuid(),
    "product_name": "volutpat quam pede",
    "product_description": "Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.\n\nCurabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.",
    "product_price": 1378.41,
    "product_category": "necklace",
    "product_brand": "Trilia",
    "product_image": "https://staticimg.titan.co.in/Tanishq/Catalog/502762NXZAA09_1.jpg?impolicy=pqmed&imwidth=640",
    "product_rating": 2.6,
    "product_reviews": 580,
    "product_color": "Platinum",
    "product_size": "medium",
    "product_material": "platinum",
    "product_occasion": "Modern",
    "product_prevPrice": 1685.99,
      "product_isFavorite": "true",
    "product_isCart": "false",
    "product_isBadge": ""
  },
  {
    "_id": uuid(),
    "product_name": "ipsum ac",
    "product_description": "Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.\n\nMauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.\n\nNullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.",
    "product_price": 873.23,
    "product_category": "necklace",
    "product_brand": "Vimbo",
    "product_image": "https://staticimg.titan.co.in/Tanishq/Catalog/50D2A1NIIAA02_1.jpg?impolicy=pqmed&imwidth=640",
    "product_rating": 2.4,
    "product_reviews": 753,
    "product_color": "Platinum",
    "product_size": "medium",
    "product_material": "gold",
    "product_occasion": "Traditional",
    "product_prevPrice": 1692.305,
    "product_isFavorite": "false",
    "product_isCart": "false",
    "product_isBadge": "New"
  },
  {
    "_id": uuid(),
    "product_name": "ipsum integer",
    "product_description": "Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.\n\nNullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.\n\nMorbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.",
    "product_price": 1090.88,
    "product_category": "necklace",
    "product_brand": "Tekfly",
    "product_image": "https://staticimg.titan.co.in/Tanishq/Catalog/50D2D1NAIAA02_1.jpg?impolicy=pqmed&imwidth=640",
    "product_rating": 3.0,
    "product_reviews": 437,
    "product_color": "pink",
    "product_size": "large",
    "product_material": "diamond",
    "product_occasion": "Engagement",
    "product_prevPrice": 2135.783,
    "product_isFavorite": "true",
    "product_isCart": "false",
    "product_isBadge": "Trending"
  },
  {
    "_id": uuid(),
    "product_name": "condimentum id",
    "product_description": "Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.\n\nCras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
    "product_price": 1236.34,
    "product_category": "necklace",
    "product_brand": "Tagtune",
    "product_image": "https://staticimg.titan.co.in/Tanishq/Catalog/50D3I1NEUAA09_1.jpg?impolicy=pqmed&imwidth=640",
    "product_rating": 4.4,
    "product_reviews": 846,
    "product_color": "pink",
    "product_size": "large",
    "product_material": "diamond",
    "product_occasion": "Casual",
    "product_prevPrice": 1612.299,
    "product_isFavorite": "false",
    "product_isCart": "false",
    "product_isBadge": ""
  },
  {
    "_id": uuid(),
    "product_name": "lobortis vel dapibus at diam",
    "product_description": "Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.\n\nMauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.",
    "product_price": 390.92,
    "product_category": "earring",
    "product_brand": "Gabvine",
    "product_image": "https://staticimg.titan.co.in/Tanishq/Catalog/50C1D1HGVABA32_1.jpg?impolicy=pqmed&imwidth=640",
    "product_rating": 2.8,
    "product_reviews": 481,
    "product_color": "green",
    "product_size": "large",
    "product_material": "platinum",
    "product_occasion": "Traditional",
    "product_prevPrice": 1791.86,
    "product_isFavorite": "true",
    "product_isCart": "false",
    "product_isBadge": "Trending"
  },
  {
    "_id": uuid(),
    "product_name": "vel enim",
    "product_description": "Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.\n\nProin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.\n\nDuis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.",
    "product_price": 647.81,
    "product_category": "earring",
    "product_brand": "Dazzlesphere",
    "product_image": "https://staticimg.titan.co.in/Tanishq/Catalog/501767HMLAAA09_1.jpg?impolicy=pqmed&imwidth=640",
    "product_rating": 3.7,
    "product_reviews": 485,
    "product_color": "Rosegold",
    "product_size": "large",
    "product_material": "diamond",
    "product_occasion": "Office",
    "product_prevPrice": 1522.013,
    "product_isFavorite": "true",
    "product_isCart": "false",
    "product_isBadge": "New"
  },
  {
    "_id": uuid(),
    "product_name": "cubilia curae",
    "product_description": "In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.\n\nSuspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.\n\nMaecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.",
    "product_price": 881.84,
    "product_category": "earring",
    "product_brand": "Innojam",
    "product_image": "https://staticimg.titan.co.in/Mia/Catalog/552822HDTAAE09_1.jpg?impolicy=pqmed&imwidth=640",
    "product_rating": 1.1,
    "product_reviews": 674,
    "product_color": "green",
    "product_size": "medium",
    "product_material": "diamond",
    "product_occasion": "Modern",
    "product_prevPrice": 2032.827,
    "product_isFavorite": "false",
    "product_isCart": "false",
    "product_isBadge": ""
  },
  {
    "_id": uuid(),
    "product_name": "ultricies eu",
    "product_description": "Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.\n\nDuis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.\n\nDonec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.",
    "product_price": 921.4,
    "product_category": "ring",
    "product_brand": "Dynazzy",
    "product_image": "https://staticimg.titan.co.in/Tanishq/Catalog/749992FCKAA04_1.jpg?impolicy=pqmed&imwidth=640",
    "product_rating": 4.1,
    "product_reviews": 879,
    "product_color": "pink",
    "product_size": "medium",
    "product_material": "platinum",
    "product_occasion": "Bridal",
    "product_prevPrice": 1748.389,
    "product_isFavorite": "true",
    "product_isCart": "false",
    "product_isBadge": ""
  },
  {
    "_id": uuid(),
    "product_name": "cubilia curae duis faucibus accumsan",
    "product_description": "Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.",
    "product_price": 1005.85,
    "product_category": "earring",
    "product_brand": "Devshare",
    "product_image": "https://staticimg.titan.co.in/Tanishq/Catalog/500104SQAABAPL_1.jpg?impolicy=pqmed&imwidth=640",
    "product_rating": 2.1,
    "product_reviews": 986,
    "product_color": "blue",
    "product_size": "large",
    "product_material": "platinum",
    "product_occasion": "Office",
    "product_prevPrice": 1596.262,
    "product_isFavorite": "true",
    "product_isCart": "false",
    "product_isBadge": "Trending"
  },
  {
    "_id": uuid(),
    "product_name": "arcu libero rutrum ac lobortis",
    "product_description": "Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.\n\nQuisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.",
    "product_price": 729.17,
    "product_category": "earring",
    "product_brand": "Yakijo",
    "product_image": "https://staticimg.titan.co.in/Tanishq/Catalog/50D2FFHGXAAA29_1.jpg?impolicy=pqmed&imwidth=640",
    "product_rating": 2.1,
    "product_reviews": 323,
    "product_color": "Silver",
    "product_size": "medium",
    "product_material": "gold",
    "product_occasion": "Office",
    "product_prevPrice": 2184.532,
    "product_isFavorite": "false",
    "product_isCart": "false",
    "product_isBadge": ""
  },
  {
    "_id": uuid(),
    "product_name": "bibendum",
    "product_description": "Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.\n\nIn congue. Etiam justo. Etiam pretium iaculis justo.",
    "product_price": 1173.79,
    "product_category": "necklace",
    "product_brand": "Skilith",
    "product_image": "https://staticimg.titan.co.in/Tanishq/Catalog/50F1D1NMHAA04_1.jpg?impolicy=pqmed&imwidth=640",
    "product_rating": 4.6,
    "product_reviews": 137,
    "product_color": "Platinum",
    "product_size": "medium",
    "product_material": "silver",
    "product_occasion": "Modern",
    "product_prevPrice": 1965.983,
    "product_isFavorite": "true",
    "product_isCart": "false",
    "product_isBadge": "Trending"
  },
  {
    "_id": uuid(),
    "product_name": "velit id",
    "product_description": "Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.\n\nMorbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.",
    "product_price": 1277.63,
    "product_category": "necklace",
    "product_brand": "Midel",
    "product_image": "https://staticimg.titan.co.in/Tanishq/Catalog/50D5PTNXLAA02_1.jpg?impolicy=pqmed&imwidth=640",
    "product_rating": 3.8,
    "product_reviews": 725,
    "product_color": "blue",
    "product_size": "small",
    "product_material": "diamond",
    "product_occasion": "Casual",
    "product_prevPrice": 2404.102,
    "product_isFavorite": "false",
    "product_isCart": "false",
    "product_isBadge": "Trending"
  },
  {
    "_id": uuid(),
    "product_name": "donec dapibus duis at",
    "product_description": "Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.\n\nCras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.\n\nProin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.",
    "product_price": 484.42,
    "product_category": "earring",
    "product_brand": "Yambee",
    "product_image": "https://staticimg.titan.co.in/Tanishq/Catalog/501166SGNABA00_1.jpg?impolicy=pqmed&imwidth=640",
    "product_rating": 3.6,
    "product_reviews": 679,
    "product_color": "Silver",
    "product_size": "large",
    "product_material": "silver",
    "product_occasion": "Traditional",
    "product_prevPrice": 2064.008,
    "product_isFavorite": "false",
    "product_isCart": "false",
    "product_isBadge": "Trending"
  },
  {
    "_id": uuid(),
    "product_name": "praesent lectus vestibulum",
    "product_description": "In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.\n\nNulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.\n\nCras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.",
    "product_price": 1470.24,
    "product_category": "earring",
    "product_brand": "Tagcat",
    "product_image": "https://staticimg.titan.co.in/Tanishq/Catalog/50D1I2DOKAAA02_1.jpg?impolicy=pqmed&imwidth=640",
    "product_rating": 1.4,
    "product_reviews": 959,
    "product_color": "Rosegold",
    "product_size": "large",
    "product_material": "silver",
    "product_occasion": "Engagement",
    "product_prevPrice": 1978.696,
    "product_isFavorite": "false",
    "product_isCart": "false",
    "product_isBadge": "Trending"
  },
  {
    "_id": uuid(),
    "product_name": "vestibulum eget vulputate ut",
    "product_description": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.",
    "product_price": 248.73,
    "product_category": "bracelet",
    "product_brand": "Buzzshare",
    "product_image": "https://staticimg.titan.co.in/Mia/Catalog/552822BPYAE09_1.jpg?impolicy=pqmed&imwidth=640",
    "product_rating": 3.8,
    "product_reviews": 387,
    "product_color": "Rosegold",
    "product_size": "extra large",
    "product_material": "diamond",
    "product_occasion": "Casual",
    "product_prevPrice": 1895.66,
    "product_isFavorite": "false",
    "product_isCart": "false",
    "product_isBadge": "New"
  },
  {
    "_id": uuid(),
    "product_name": "interdum venenatis",
    "product_description": "Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.",
    "product_price": 214.0,
    "product_category": "ring",
    "product_brand": "Skyvu",
    "product_image": "https://staticimg.titan.co.in/Tanishq/Catalog/510429FFAAA00_1.jpg?impolicy=pqmed&imwidth=640",
    "product_rating": 4.6,
    "product_reviews": 584,
    "product_color": "Gold",
    "product_size": "extra large",
    "product_material": "gold",
    "product_occasion": "Casual",
    "product_prevPrice": 1951.787,
    "product_isFavorite": "true",
    "product_isCart": "false",
    "product_isBadge": "Trending"
  },
  {
    "_id": uuid(),
    "product_name": "malesuada in imperdiet et commodo",
    "product_description": "Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.\n\nProin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.\n\nAenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.",
    "product_price": 1154.12,
    "product_category": "ring",
    "product_brand": "Vinder",
    "product_image": "https://kinclimg7.bluestone.com/f_webp,c_scale,w_1024,b_rgb:f0f0f0/giproduct/BIAB0101R04_WAA18DIG6XXXXXXXX_ABCD00-PICS-00001-1024-7197.png",
    "product_rating": 1.6,
    "product_reviews": 253,
    "product_color": "Silver",
    "product_size": "small",
    "product_material": "diamond",
    "product_occasion": "Traditional",
    "product_prevPrice": 1511.774,
    "product_isFavorite": "false",
    "product_isCart": "false",
    "product_isBadge": "New"
  },
  {
    "_id": uuid(),
    "product_name": "id",
    "product_description": "Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.\n\nDuis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.",
    "product_price": 652.55,
    "product_category": "bracelet",
    "product_brand": "Jaxspan",
    "product_image": "https://cdn.shopify.com/s/files/1/0259/0713/files/jewelove-unique-japanese-platinum-bracelet-jl-ptb-739-bracelet-38667844813041_grande.jpg?v=1682578269",
    "product_rating": 5.0,
    "product_reviews": 178,
    "product_color": "Silver",
    "product_size": "extra large",
    "product_material": "platinum",
    "product_occasion": "Bridal",
    "product_prevPrice": 1854.161,
    "product_isFavorite": "true",
    "product_isCart": "false",
    "product_isBadge": ""
  },
  {
    "_id": uuid(),
    "product_name": "consectetuer adipiscing",
    "product_description": "Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.\n\nDuis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.\n\nDonec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.",
    "product_price": 542.66,
    "product_category": "earring",
    "product_brand": "Leexo",
    "product_image": "https://staticimg.titan.co.in/Tanishq/Catalog/50F1D1DFYAGA02_1.jpg?impolicy=pqmed&imwidth=640",
    "product_rating": 2.0,
    "product_reviews": 545,
    "product_color": "Silver",
    "product_size": "large",
    "product_material": "silver",
    "product_occasion": "Modern",
    "product_prevPrice": 1775.783,
    "product_isFavorite": "true",
    "product_isCart": "false",
    "product_isBadge": ""
  },
  {
    "_id": uuid(),
    "product_name": "in sagittis dui vel nisl",
    "product_description": "Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.\n\nIn hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.\n\nAliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.",
    "product_price": 599.58,
    "product_category": "necklace",
    "product_brand": "BlogXS",
    "product_image": "https://staticimg.titan.co.in/Tanishq/Catalog/50D3I1NEQAA09_1.jpg?impolicy=pqmed&imwidth=640",
    "product_rating": 1.3,
    "product_reviews": 445,
    "product_color": "blue",
    "product_size": "large",
    "product_material": "platinum",
    "product_occasion": "Modern",
    "product_prevPrice": 2062.255,
    "product_isFavorite": "true",
    "product_isCart": "false",
    "product_isBadge": "New"
  },
  {
    "_id": uuid(),
    "product_name": "ultrices",
    "product_description": "Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.",
    "product_price": 1287.77,
    "product_category": "ring",
    "product_brand": "Devshare",
    "product_image": "https://staticimg.titan.co.in/Tanishq/Catalog/741188FNCAA02_1.jpg?impolicy=pqmed&imwidth=640",
    "product_rating": 4.3,
    "product_reviews": 344,
    "product_color": "green",
    "product_size": "medium",
    "product_material": "platinum",
    "product_occasion": "Engagement",
    "product_prevPrice": 1570.8,
    "product_isFavorite": "false",
    "product_isCart": "false",
    "product_isBadge": "New"
  },
  {
    "_id": uuid(),
    "product_name": "ipsum",
    "product_description": "Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.",
    "product_price": 1253.74,
    "product_category": "ring",
    "product_brand": "Bluezoom",
    "product_image": "https://staticimg.titan.co.in/Tanishq/Catalog/749992FDDAA02_1.jpg?impolicy=pqmed&imwidth=640",
    "product_rating": 1.6,
    "product_reviews": 926,
    "product_color": "pink",
    "product_size": "large",
    "product_material": "diamond",
    "product_occasion": "Modern",
    "product_prevPrice": 1602.2,
    "product_isFavorite": "false",
    "product_isCart": "false",
    "product_isBadge": "New"
  },
  {
    "_id": uuid(),
    "product_name": "vestibulum",
    "product_description": "Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.\n\nInteger tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.",
    "product_price": 798.16,
    "product_category": "necklace",
    "product_brand": "Zazio",
    "product_image": "https://images.cltstatic.com/media/product/350/AL00297-SS0000-anne-shirley-necklace-in--oxidised-silver-prd-1-model.jpg",
    "product_rating": 4.5,
    "product_reviews": 528,
    "product_color": "pink",
    "product_size": "medium",
    "product_material": "silver",
    "product_occasion": "Bridal",
    "product_prevPrice": 2385.398,
    "product_isFavorite": "false",
    "product_isCart": "false",
    "product_isBadge": ""
  },
  {
    "_id": uuid(),
    "product_name": "in quis justo",
    "product_description": "Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.\n\nPraesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.\n\nMorbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.",
    "product_price": 835.77,
    "product_category": "necklace",
    "product_brand": "Divape",
    "product_image": "https://staticimg.titan.co.in/Tanishq/Catalog/50D3B4NMVAA02_1.jpg?impolicy=pqmed&imwidth=640",
    "product_rating": 1.7,
    "product_reviews": 141,
    "product_color": "green",
    "product_size": "small",
    "product_material": "gold",
    "product_occasion": "Casual",
    "product_prevPrice": 2254.336,
    "product_isFavorite": "false",
    "product_isCart": "false",
    "product_isBadge": "New"
  },
  {
    "_id": uuid(),
    "product_name": "in magna bibendum",
    "product_description": "Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.",
    "product_price": 1006.31,
    "product_category": "bracelet",
    "product_brand": "Dabfeed",
    "product_image": "https://images.cltstatic.com/media/product/350/AT00345-SS0000-feeling-hmeltha-oxidised-bracelet-in--silver-prd-1-model.jpg",
    "product_rating": 1.0,
    "product_reviews": 942,
    "product_color": "green",
    "product_size": "large",
    "product_material": "silver",
    "product_occasion": "Modern",
    "product_prevPrice": 1961.942,
    "product_isFavorite": "true",
    "product_isCart": "false",
    "product_isBadge": ""
  },
  {
    "_id": uuid(),
    "product_name": "sed",
    "product_description": "Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.\n\nProin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.\n\nDuis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.",
    "product_price": 1038.64,
    "product_category": "bracelet",
    "product_brand": "Meetz",
    "product_image": "https://images.cltstatic.com/media/product/350/AT00032-SS0000-oxidised-so-versatile-bracelet-in--silver-prd-1-base.jpg",
    "product_rating": 4.3,
    "product_reviews": 964,
    "product_color": "Gold",
    "product_size": "large",
    "product_material": "silver",
    "product_occasion": "Bridal",
    "product_prevPrice": 1514.927,
    "product_isFavorite": "true",
    "product_isCart": "false",
    "product_isBadge": ""
  },
  {
    "_id": uuid(),
    "product_name": "semper",
    "product_description": "Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.\n\nNullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.\n\nIn quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.",
    "product_price": 859.47,
    "product_category": "bracelet",
    "product_brand": "Wordtune",
    "product_image": "https://cdn.shopify.com/s/files/1/0259/0713/files/jewelove-platinum-evara-indo-western-diamond-bracelet-for-women-jl-ptb-638-38712522801393_grande.jpg?v=1682565310",
    "product_rating": 2.0,
    "product_reviews": 145,
    "product_color": "Gold",
    "product_size": "small",
    "product_material": "platinum",
    "product_occasion": "Engagement",
    "product_prevPrice": 2097.406,
    "product_isFavorite": "true",
    "product_isCart": "false",
    "product_isBadge": "Trending"
  }
]
